### Crear Producto
POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "Sandalas",
  "description": "Sandalias de goma ultraligeras, resistentes al agua y fáciles de limpiar.",
  "price": 35000,
  "stock": 200,
  "brand": "Crocs",
  "gender": "Niños",
  "isActive": true,
  "categoryId": "2a98f231-577a-4c73-8393-46eba1666b41",
  "images": [
    "https://example.com/imagen1.jpg",
    "https://example.com/imagen2.jpg"
  ],
  "options": {
    "color": [
      "Rojo",
      "Azul",
      "Negro"
    ],
    "talla": [
      39,
      40,
      41,
      42,
      43
    ]
  }
}


###Obtiene todos los productos
GET http://localhost:3001/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZWU0MDJhZS05YTAzLTQ4MmItODFhMi1iM2JiMmY3ZGUzZDYiLCJlbWFpbCI6ImxhdXJhbXVzc2E5NEBnbWFpbC5jb20iLCJpYXQiOjE3NjU1MTczNzIsImV4cCI6MTc2NTYwMzc3Mn0.WXsiqOwytldCa4bE2HNgPjEq4ODsEVFq6o9xmBmfr48


###Obtiene un producto por id
GET http://localhost:3001/products/4aeea243-7f9f-4c22-9584-e386fbd2471d
Content-Type: application/json


###Obtiene los 5 productos mas vendidos 
GET http://localhost:3001/products/top-selling
Content-Type: application/json


###Modifica un producto producto
PATCH http://localhost:3001/products/922759a1-78f1-4804-b529-52ae1ce4aeae
Content-Type: application/json

{
  "name": "Zapatillas Running",
  "options": {
    "talla": [
      45,
      48
    ]
  }
}


###Soft delete 
DELETE http://localhost:3001/products/922759a1-78f1-4804-b529-52ae1ce4aeae
Content-Type: application/json