### Crear una venta
POST http://localhost:3001/sales
Content-Type: application/json
# Authorization: Bearer token

{
  "customerId": "4b2fca4f-9541-42c9-b249-22e73512d027",
  "paymentStatus": "FAILED",
  "paymentMethod": "DEBIT_CARD",
  "status": "PENDING",
  "items": [
    {
      "productId": "3187990d-5360-4f66-9159-8a426ecc757b",
      "quantity": 2
    },
    {
      "productId": "dbacd5a8-061c-4bab-9592-2f5081cd53ba",
      "quantity": 1
    }
  ]
}


### Obtener todas las ventas
GET http://localhost:3001/sales
Content-Type: application/json


### Obtener una sola venta
GET http://localhost:3001/sales/c9c71ed0-6910-44f2-a5cf-08e2b4ee6f8d
Content-Type: application/json


### Modificar order status
PATCH http://localhost:3001/sales/08b44e48-19e0-4e80-a078-2217032cc6c7
Content-Type: application/json

{
  "status": "DELIVERED",
  "trackingId":""
}


# PENDING: 'PENDING',
#   PREPARING: 'PREPARING',
#   SHIPPED: 'SHIPPED',
#   DELIVERED: 'DELIVERED',
#   CANCELLED: 'CANCELLED'