### Crear una venta
POST http://localhost:3001/sales
Content-Type: application/json
# Authorization: Bearer token

{
  "customerId": "4b2fca4f-9541-42c9-b249-22e73512d027",
  "paymentStatus": "FAILED",
  "paymentMethod": "DEBIT_CARD",
  "status": "PENDING",
  "items": [
    {
      "productId": "3187990d-5360-4f66-9159-8a426ecc757b",
      "quantity": 2
    },
    {
      "productId": "dbacd5a8-061c-4bab-9592-2f5081cd53ba",
      "quantity": 1
    }
  ]
}


### Obtener todas las ventas
GET http://localhost:3001/sales
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YmI4OGEwNS0zNThhLTRiODEtODE0Mi03NjhiNmU0MWQ1ZDYiLCJlbWFpbCI6ImxhdXJhbXVzc2E5NEBnbWFpbC5jb20iLCJpYXQiOjE3NjU2MzUyMDYsImV4cCI6MTc2NTcyMTYwNn0.SnWpJpVjCIVV9396NhiNE-oOVftzLeuGHJpFrEbMVKw



### Obtener una sola venta
GET http://localhost:3001/sales/27b04aaa-698e-48fb-91a7-d472d3d7191f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YmI4OGEwNS0zNThhLTRiODEtODE0Mi03NjhiNmU0MWQ1ZDYiLCJlbWFpbCI6ImxhdXJhbXVzc2E5NEBnbWFpbC5jb20iLCJpYXQiOjE3NjU2MzUyMDYsImV4cCI6MTc2NTcyMTYwNn0.SnWpJpVjCIVV9396NhiNE-oOVftzLeuGHJpFrEbMVKw

### Modificar order status
PATCH http://localhost:3001/sales/27b04aaa-698e-48fb-91a7-d472d3d7191f
Content-Type: application/json

{
  "status": "DELIVERED",
  "trackingId":""
}


# PENDING: 'PENDING',
#   PREPARING: 'PREPARING',
#   SHIPPED: 'SHIPPED',
#   DELIVERED: 'DELIVERED',
#   CANCELLED: 'CANCELLED'